### ISSUE TITLE
Use GFM for markdown

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/blog#9]
``` yaml
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
```

From https://github.com/docker/docker.github.io/blob/master/_config.yml
